name: Build and Release Project
on: [ workflow_dispatch ]
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Execute Gradle Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
    - name: Publish Pre Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          build/libs/*.jar
